### ISSUE TITLE
Dark mode and theme toggle

### ISSUE THREAD

**Issue by xXBlackHawkXx** [gobeam/truthy-react-frontend#7]
**Is your feature request related to a problem? Please describe.**
With the increasing popularity of a dark mode, it would be nice for it to be implemented here.

**Describe the solution you'd like**
A toggle switch should be added perhaps either in the header or navbar?

**Comment by gobeam** [comment]
I've been planning for this feature from the beginning. The designer who volunteered for this project is a bit busy currently and I'm not so good at the design part. If you have that expertise you're more than welcome to collaborate in this project.

**Comment by gobeam** [comment]
Since we don't have any updates on this, I will be closing this issue for now
