### ISSUE TITLE
Remember me not working

### ISSUE THREAD

**Issue by xXBlackHawkXx** [gobeam/truthy-react-frontend#8]
**Describe the bug**
It appeard that the remember me functionality is not working after the 15 minute expiration with a page reload. I'd expect the page to just refresh, however I get redirected to the login page as the session has expired.

**To Reproduce**
1. Log in with the remember me checkbox ticked.
2. Wait 15 mins.
3. Refresh the page.

**Expected behavior**
I would expect the page to simply reload and stay logged in.

**Comment by gobeam** [comment]
@xXBlackHawkXx  This bug is actually from the backend side where refresh token expiry was not being set properly and has been fixed. Feel free to reopen if you think the issue still prevails.
